

const db = [
    {
      id: "p1",
      title: "Kotlin multithreading: Comparing .wait(), .sleep(), and .delay()",
      image: "/3236267.jpg",
      post: " The wait, sleep, and delay Kotlin multithreading functions control the flow and order of execution of different streams of execution of different streams of",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p2",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p3",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p4",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p5",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p6",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p7",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p8",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p9",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p10",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p11",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p12",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p13",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p14",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p15",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p16",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p17",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p18",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p19",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p20",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p21",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p22",
      title: "Setting up visual regression testing with React Native Owl",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
    {
      id: "p23",
      title: "Setting up visual regression testing with React Native Owl 20",
      image: "/3236267.jpg",
      post: " In this post, we will take a look at writing visual regression tests for React Native applications using React. In this post, we will take a look at writing visual regression tests for React Native applications using React",
      author: "Rahul Padalkar",
      authorImg: "/3236267.jpg",
      date: "Apr 19, 2023",
      time: "4 min read",
    },
  ];
  
  export default db;